/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTutorialRouteImport } from './routes/api/tutorial'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTutoriaisRouteImport } from './routes/_authenticated/app.tutoriais'
import { Route as AuthenticatedAppTintasRouteImport } from './routes/_authenticated/app.tintas'
import { Route as AuthenticatedAppSimuladorRouteImport } from './routes/_authenticated/app.simulador'
import { Route as AuthenticatedAppMedicoesRouteImport } from './routes/_authenticated/app.medicoes'
import { Route as AuthenticatedAppMateriaisRouteImport } from './routes/_authenticated/app.materiais'
import { Route as AuthenticatedAppIaRouteImport } from './routes/_authenticated/app.ia'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/app.financeiro'
import { Route as AuthenticatedAppDecoracaoRouteImport } from './routes/_authenticated/app.decoracao'
import { Route as AuthenticatedAppChecklistRouteImport } from './routes/_authenticated/app.checklist'
import { Route as AuthenticatedAppCameraRouteImport } from './routes/_authenticated/app.camera'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as AuthenticatedAppProjetosIndexRouteImport } from './routes/_authenticated/app.projetos.index'
import { Route as AuthenticatedAppProjetosIdRouteImport } from './routes/_authenticated/app.projetos.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorialRoute = ApiTutorialRouteImport.update({
  id: '/api/tutorial',
  path: '/api/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTutoriaisRoute =
  AuthenticatedAppTutoriaisRouteImport.update({
    id: '/tutoriais',
    path: '/tutoriais',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTintasRoute = AuthenticatedAppTintasRouteImport.update({
  id: '/tintas',
  path: '/tintas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSimuladorRoute =
  AuthenticatedAppSimuladorRouteImport.update({
    id: '/simulador',
    path: '/simulador',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMedicoesRoute =
  AuthenticatedAppMedicoesRouteImport.update({
    id: '/medicoes',
    path: '/medicoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMateriaisRoute =
  AuthenticatedAppMateriaisRouteImport.update({
    id: '/materiais',
    path: '/materiais',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIaRoute = AuthenticatedAppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDecoracaoRoute =
  AuthenticatedAppDecoracaoRouteImport.update({
    id: '/decoracao',
    path: '/decoracao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChecklistRoute =
  AuthenticatedAppChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCameraRoute = AuthenticatedAppCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProjetosIndexRoute =
  AuthenticatedAppProjetosIndexRouteImport.update({
    id: '/projetos/',
    path: '/projetos/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjetosIdRoute =
  AuthenticatedAppProjetosIdRouteImport.update({
    id: '/projetos/$id',
    path: '/projetos/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tutorial': typeof ApiTutorialRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/camera': typeof AuthenticatedAppCameraRoute
  '/app/checklist': typeof AuthenticatedAppChecklistRoute
  '/app/decoracao': typeof AuthenticatedAppDecoracaoRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/ia': typeof AuthenticatedAppIaRoute
  '/app/materiais': typeof AuthenticatedAppMateriaisRoute
  '/app/medicoes': typeof AuthenticatedAppMedicoesRoute
  '/app/simulador': typeof AuthenticatedAppSimuladorRoute
  '/app/tintas': typeof AuthenticatedAppTintasRoute
  '/app/tutoriais': typeof AuthenticatedAppTutoriaisRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/projetos/$id': typeof AuthenticatedAppProjetosIdRoute
  '/app/projetos/': typeof AuthenticatedAppProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tutorial': typeof ApiTutorialRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/camera': typeof AuthenticatedAppCameraRoute
  '/app/checklist': typeof AuthenticatedAppChecklistRoute
  '/app/decoracao': typeof AuthenticatedAppDecoracaoRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/ia': typeof AuthenticatedAppIaRoute
  '/app/materiais': typeof AuthenticatedAppMateriaisRoute
  '/app/medicoes': typeof AuthenticatedAppMedicoesRoute
  '/app/simulador': typeof AuthenticatedAppSimuladorRoute
  '/app/tintas': typeof AuthenticatedAppTintasRoute
  '/app/tutoriais': typeof AuthenticatedAppTutoriaisRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/projetos/$id': typeof AuthenticatedAppProjetosIdRoute
  '/app/projetos': typeof AuthenticatedAppProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tutorial': typeof ApiTutorialRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/camera': typeof AuthenticatedAppCameraRoute
  '/_authenticated/app/checklist': typeof AuthenticatedAppChecklistRoute
  '/_authenticated/app/decoracao': typeof AuthenticatedAppDecoracaoRoute
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/app/ia': typeof AuthenticatedAppIaRoute
  '/_authenticated/app/materiais': typeof AuthenticatedAppMateriaisRoute
  '/_authenticated/app/medicoes': typeof AuthenticatedAppMedicoesRoute
  '/_authenticated/app/simulador': typeof AuthenticatedAppSimuladorRoute
  '/_authenticated/app/tintas': typeof AuthenticatedAppTintasRoute
  '/_authenticated/app/tutoriais': typeof AuthenticatedAppTutoriaisRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/projetos/$id': typeof AuthenticatedAppProjetosIdRoute
  '/_authenticated/app/projetos/': typeof AuthenticatedAppProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/app'
    | '/api/chat'
    | '/api/tutorial'
    | '/app/agenda'
    | '/app/camera'
    | '/app/checklist'
    | '/app/decoracao'
    | '/app/financeiro'
    | '/app/ia'
    | '/app/materiais'
    | '/app/medicoes'
    | '/app/simulador'
    | '/app/tintas'
    | '/app/tutoriais'
    | '/app/'
    | '/app/projetos/$id'
    | '/app/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/tutorial'
    | '/app/agenda'
    | '/app/camera'
    | '/app/checklist'
    | '/app/decoracao'
    | '/app/financeiro'
    | '/app/ia'
    | '/app/materiais'
    | '/app/medicoes'
    | '/app/simulador'
    | '/app/tintas'
    | '/app/tutoriais'
    | '/app'
    | '/app/projetos/$id'
    | '/app/projetos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/api/chat'
    | '/api/tutorial'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/camera'
    | '/_authenticated/app/checklist'
    | '/_authenticated/app/decoracao'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/ia'
    | '/_authenticated/app/materiais'
    | '/_authenticated/app/medicoes'
    | '/_authenticated/app/simulador'
    | '/_authenticated/app/tintas'
    | '/_authenticated/app/tutoriais'
    | '/_authenticated/app/'
    | '/_authenticated/app/projetos/$id'
    | '/_authenticated/app/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTutorialRoute: typeof ApiTutorialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutorial': {
      id: '/api/tutorial'
      path: '/api/tutorial'
      fullPath: '/api/tutorial'
      preLoaderRoute: typeof ApiTutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tutoriais': {
      id: '/_authenticated/app/tutoriais'
      path: '/tutoriais'
      fullPath: '/app/tutoriais'
      preLoaderRoute: typeof AuthenticatedAppTutoriaisRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tintas': {
      id: '/_authenticated/app/tintas'
      path: '/tintas'
      fullPath: '/app/tintas'
      preLoaderRoute: typeof AuthenticatedAppTintasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/simulador': {
      id: '/_authenticated/app/simulador'
      path: '/simulador'
      fullPath: '/app/simulador'
      preLoaderRoute: typeof AuthenticatedAppSimuladorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/medicoes': {
      id: '/_authenticated/app/medicoes'
      path: '/medicoes'
      fullPath: '/app/medicoes'
      preLoaderRoute: typeof AuthenticatedAppMedicoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/materiais': {
      id: '/_authenticated/app/materiais'
      path: '/materiais'
      fullPath: '/app/materiais'
      preLoaderRoute: typeof AuthenticatedAppMateriaisRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ia': {
      id: '/_authenticated/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AuthenticatedAppIaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/decoracao': {
      id: '/_authenticated/app/decoracao'
      path: '/decoracao'
      fullPath: '/app/decoracao'
      preLoaderRoute: typeof AuthenticatedAppDecoracaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/checklist': {
      id: '/_authenticated/app/checklist'
      path: '/checklist'
      fullPath: '/app/checklist'
      preLoaderRoute: typeof AuthenticatedAppChecklistRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/camera': {
      id: '/_authenticated/app/camera'
      path: '/camera'
      fullPath: '/app/camera'
      preLoaderRoute: typeof AuthenticatedAppCameraRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projetos/': {
      id: '/_authenticated/app/projetos/'
      path: '/projetos'
      fullPath: '/app/projetos/'
      preLoaderRoute: typeof AuthenticatedAppProjetosIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projetos/$id': {
      id: '/_authenticated/app/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/app/projetos/$id'
      preLoaderRoute: typeof AuthenticatedAppProjetosIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppCameraRoute: typeof AuthenticatedAppCameraRoute
  AuthenticatedAppChecklistRoute: typeof AuthenticatedAppChecklistRoute
  AuthenticatedAppDecoracaoRoute: typeof AuthenticatedAppDecoracaoRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppIaRoute: typeof AuthenticatedAppIaRoute
  AuthenticatedAppMateriaisRoute: typeof AuthenticatedAppMateriaisRoute
  AuthenticatedAppMedicoesRoute: typeof AuthenticatedAppMedicoesRoute
  AuthenticatedAppSimuladorRoute: typeof AuthenticatedAppSimuladorRoute
  AuthenticatedAppTintasRoute: typeof AuthenticatedAppTintasRoute
  AuthenticatedAppTutoriaisRoute: typeof AuthenticatedAppTutoriaisRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppProjetosIdRoute: typeof AuthenticatedAppProjetosIdRoute
  AuthenticatedAppProjetosIndexRoute: typeof AuthenticatedAppProjetosIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppCameraRoute: AuthenticatedAppCameraRoute,
  AuthenticatedAppChecklistRoute: AuthenticatedAppChecklistRoute,
  AuthenticatedAppDecoracaoRoute: AuthenticatedAppDecoracaoRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppIaRoute: AuthenticatedAppIaRoute,
  AuthenticatedAppMateriaisRoute: AuthenticatedAppMateriaisRoute,
  AuthenticatedAppMedicoesRoute: AuthenticatedAppMedicoesRoute,
  AuthenticatedAppSimuladorRoute: AuthenticatedAppSimuladorRoute,
  AuthenticatedAppTintasRoute: AuthenticatedAppTintasRoute,
  AuthenticatedAppTutoriaisRoute: AuthenticatedAppTutoriaisRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppProjetosIdRoute: AuthenticatedAppProjetosIdRoute,
  AuthenticatedAppProjetosIndexRoute: AuthenticatedAppProjetosIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTutorialRoute: ApiTutorialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
